### ISSUE TITLE
Can I use it with typescript?

### ISSUE THREAD

**Issue by gustawdaniel** [lukeed/uid#2]
In node js

```
import uid from 'uid';
``` 

works but in typescript (nexus graphql) i have undefined.

**Comment by gustawdaniel** [comment]
I fixed by 

```
import * as uid from 'uid';
```

this can be problem of nexus or typescript rather than this package.

**Comment by lukeed** [comment]
Hey, I think this is related to your nexus graph stuff. Have never used it, but I use your original snippet everywhere in TS and it works as expected
