### ISSUE TITLE
uid is not a function in 2.0.0 version

### ISSUE THREAD

**Issue by fabiantoth** [lukeed/uid#5]
Receiving a TypeError: uid is not a function on v2.0.0

It works fine when I switch back to v1.0.0 . Was running a jest test on node v12.7.0 took me a sec to realize version was upgraded...

**Comment by lukeed** [comment]
Hi, there are always breaking changes between major versions. In `uid` case, it was re: imports

https://github.com/lukeed/uid/releases/tag/v2.0.0

**Comment by fabiantoth** [comment]
Thank you for clarification, was able to make the quick fix!
