### ISSUE TITLE
Readme relates to version 1.0.0

### ISSUE THREAD

**Issue by antony** [lukeed/uid#6]
Took me a while to figure out what is going on, but the readme seems to need upating for v2.0.0

v2.0.0 generates only hexadecimal UIDs, greatly increasing the risk of collision with shorter strings. The readme suggests a dictionary of a-z0-9 but it's actually just a-e0-9.

The example output should be changed too.

Happy to open a PR for this - but incidentally, why the change in v2? The output of v1 is more useful to me so I may have to pin it at 1 - but is there an issue with the older version?

**Comment by lukeed** [comment]
Ah right, just the example outputs & the `a-z` part need updating.

There was no issue with 1.0, it was `a-z0-9` but produced 11-char strings at 5M ops/sec instead of the current 24M ops/sec.

Maybe I'll bring back 1.0 code as `uid/alphanum` module?
